import React, { useState } from 'react';
import { Button, Card } from '../components/UIComponents';
import * as Storage from '../services/storageService';
import { analyzeBloodTrends } from '../services/geminiService';
import { Sparkles, AlertTriangle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface AIInsightsPageProps {
  refreshTrigger: number;
}

const AIInsightsPage: React.FC<AIInsightsPageProps> = ({ refreshTrigger }) => {
  const [analysis, setAnalysis] = useState<string>('');
  const [loading, setLoading] = useState(false);

  const handleAnalyze = async () => {
    setLoading(true);
    const records = Storage.getRecords();
    const profile = Storage.getProfile();
    const result = await analyzeBloodTrends(records, profile);
    setAnalysis(result);
    setLoading(false);
  };

  return (
    <div className="p-6 min-h-screen">
      <div className="flex flex-col items-center text-center mb-8">
        <div className="bg-indigo-100 p-4 rounded-full mb-4">
            <Sparkles className="text-indigo-600" size={32} />
        </div>
        <h1 className="text-2xl font-bold text-slate-900">AI Health Assistant</h1>
        <p className="text-slate-500 text-sm mt-2 max-w-xs">
          Generate a summary of your recent blood count trends using AI.
        </p>
      </div>

      <div className="bg-amber-50 border border-amber-100 p-4 rounded-xl flex gap-3 items-start mb-6">
        <AlertTriangle className="text-amber-500 shrink-0 mt-0.5" size={18} />
        <p className="text-xs text-amber-800 leading-relaxed">
          <strong>Disclaimer:</strong> This analysis is generated by AI (Gemini) and does not constitute medical advice. Always consult your oncologist for interpretation of your blood results.
        </p>
      </div>

      {!analysis && (
        <Button 
            onClick={handleAnalyze} 
            disabled={loading}
            className="bg-indigo-600 shadow-indigo-200 hover:bg-indigo-700"
        >
            {loading ? 'Analyzing Records...' : 'Analyze Recent Trends'}
        </Button>
      )}

      {analysis && (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            <Card className="bg-white border-indigo-100 shadow-lg shadow-indigo-50/50">
                <div className="prose prose-sm prose-indigo max-w-none">
                    <ReactMarkdown>{analysis}</ReactMarkdown>
                </div>
            </Card>
            <div className="mt-6">
                <Button variant="secondary" onClick={() => setAnalysis('')}>Clear & Start Over</Button>
            </div>
        </div>
      )}
    </div>
  );
};

export default AIInsightsPage;